### ISSUE TITLE
comments after brackets

### ISSUE THREAD

**Issue by burner1024** [wipe2238/ScanMsg#1]
Many comments seem to be like this, maybe it's worth allowing them too?

```
{109}{}{Klamath}                          // .MAP  ;Downtown
----------------^ text after brackets [game\map.msg:28]
{110}{}{Klamath}                          // .MAP  ;Mall
----------------^ text after brackets [game\map.msg:29]
{111}{}{Klamath}                          // .MAP  ;Rat Caves
----------------^ text after brackets [game\map.msg:30]
{112}{}{Klamath}                          // .MAP  ;Toxic Caves
----------------^ text after brackets [game\map.msg:31]
{113}{}{Klamath}                          // .MAP  ;Trapping Caves
----------------^ text after brackets [game\map.msg:32]
```

**Comment by wipe2238** [comment]
You can run with `--relaxed` switch, which allows `//` and `;` comments; there's no other effects for that option for now.
It's also available when running as action:
```yml
- uses: wipe2238/ScanMsg@master
  with:
   path:    path/to/text/english/
   relaxed: true
```

**Comment by burner1024** [comment]
I mean same line comments. The output is already with `--relaxed`.

**Comment by wipe2238** [comment]
This can't be right, map.msg is the reason option exists 😕

```
$ cat ScanMsg/Build/i1/after.msg
{109}{}{Klamath}                          // .MAP  ;Downtown
{110}{}{Klamath}                          // .MAP  ;Mall
{111}{}{Klamath}                          // .MAP  ;Rat Caves
{112}{}{Klamath}                          // .MAP  ;Toxic Caves
{113}{}{Klamath}                          // .MAP  ;Trapping Caves
```

Strict mode
```
$ dotnet run --project ScanMsg/ScanMsg.NET5.csproj ScanMsg/Build/i1/
Scanning files... 1 found
{109}{}{Klamath}                          // .MAP  ;Downtown
----------------^ text after brackets [ScanMsg\Build\i1\after.msg:1]
{110}{}{Klamath}                          // .MAP  ;Mall
----------------^ text after brackets [ScanMsg\Build\i1\after.msg:2]
{111}{}{Klamath}                          // .MAP  ;Rat Caves
----------------^ text after brackets [ScanMsg\Build\i1\after.msg:3]
{112}{}{Klamath}                          // .MAP  ;Toxic Caves
----------------^ text after brackets [ScanMsg\Build\i1\after.msg:4]
{113}{}{Klamath}                          // .MAP  ;Trapping Caves
----------------^ text after brackets [ScanMsg\Build\i1\after.msg:5]
```

Relaxed mode
```
$ dotnet run --project ScanMsg/ScanMsg.NET5.csproj ScanMsg/Build/i1/ --relaxed
Scanning files... 1 found
```

Either i'm completely misreading what's happening/should happen, or something else going on (using version older than da8f3831aea215013c503f775774ffac73516a07, checking wrong ScanMsg.log, `--relaxed` switch got lost somewhere, ???)

**Comment by burner1024** [comment]
I used https://github.com/rotators/Fo1in2/blob/master/Tools/ScanMsg/ScanMsg.exe, assumed that was the latest.

**Comment by wipe2238** [comment]
Depends when it was, FO1@2 autoupdate can disable itself if repo isn't active (no human-made commits) for some time, and happens with a delay... (i think option didn't exists yet at the time i opened RPU issue).

I'll start adding .exe as an artifact to each commit from now on, to no longer depend on 1@2 update logic for binaries.

When/if using tool from GitHub's CI, i'd recommend using an action, as it always runs latest version and saves time with keeping whole thing up-to-date, as it does not require .exe to be present in repo.
Over the weekend i'll add more detailed info about inputs and some more examples to [action.yml](https://github.com/wipe2238/ScanMsg/blob/master/action.yml).

**Comment by burner1024** [comment]
> Depends when it was

Right now, still same.
The action works on linux?

**Comment by wipe2238** [comment]
> Right now, still same.

Cannot reproduce. As soon i enable relaxed mode, `text after brackets` error disappears as it should.
[Here](https://github.com/wipe2238/ScanMsg/runs/2478862766?check_suite_focus=true#step:5:781) is strict RPU scan.
[Here](https://github.com/wipe2238/ScanMsg/runs/2478862766?check_suite_focus=true#step:6:651) is relaxed RPU scan.
Files are checked alphabetically, so `game/map.msg` should show up right before `game/proitem.msg`
No clue why relaxed mode doesn't work for you... :/

I get same results when running .exe from FO1@2

> The action works on linux?

Yes, it should work on all platforms.

**Comment by burner1024** [comment]
OK, I'll just use the gha version then. Thanks.
